backend:
  name: github
  repo: Matheusesp1/RangelRadaeliAdvocacia
  branch: main

media_folder: assets/images

collections:
  - name: artigos
    label: Artigos
    label_singular: Artigo
    folder: artigos
    create: true
    slug: "{{slug}}"
    extension: html
    format: frontmatter
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Data, name: date, widget: datetime, format: "DD [de] MMMM [de] YYYY", date_format: "DD/MM/YYYY", time_format: false }
      - { label: Categoria, name: categoria, widget: string }
      - { label: Resumo, name: resumo, widget: text }
      - { label: Conteúdo, name: body, widget: markdown }